sudo: false

language: go

go:
 - 1.3.3
 - 1.4.1
 - tip

env:
  global:
   - secure: "ZxItEYtjI86c184sG1Eqqnv3f3o8qGK4hcElBFxh1haG4e7x+gzKWNziWJ9ZUCxNyZUlMzqCRv8+k74/BpR3n9j9+Wwf/I2x+sCPeCX/ac93+MKx37bkOdOciwrWXUy9Zebysu+n9i2dOvP2RCC8zJcr7gdEuqg1kRvHrwOzVBo="

before_install:
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
 - go get github.com/mattn/goveralls

script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("")
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash .test-coverage.sh; fi

after_failure: failure

notifications:
  email:
    recipients:
      - jonathan.lawlor@gmail.com
    on_success: change
    on_failure: always
